# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\GUI\configures.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ConfiguresUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(634, 394)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 621, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.groupBox = QtWidgets.QGroupBox(self.General)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 591, 71))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 41))
        self.label.setObjectName("label")
        self.DriveFolderIDEdit = QtWidgets.QLineEdit(self.groupBox)
        self.DriveFolderIDEdit.setGeometry(QtCore.QRect(210, 30, 351, 21))
        self.DriveFolderIDEdit.setObjectName("DriveFolderIDEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.General)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 591, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.SaveFilePathEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.SaveFilePathEdit.setGeometry(QtCore.QRect(210, 60, 291, 21))
        self.SaveFilePathEdit.setReadOnly(True)
        self.SaveFilePathEdit.setObjectName("SaveFilePathEdit")
        self.SelectSaveFilePathButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SelectSaveFilePathButton.setGeometry(QtCore.QRect(520, 60, 41, 21))
        self.SelectSaveFilePathButton.setObjectName("SelectSaveFilePathButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 91, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 101, 21))
        self.label_3.setObjectName("label_3")
        self.TimeRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.TimeRadioButton.setGeometry(QtCore.QRect(220, 100, 71, 21))
        self.TimeRadioButton.setObjectName("TimeRadioButton")
        self.OldRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.OldRadioButton.setGeometry(QtCore.QRect(350, 100, 71, 21))
        self.OldRadioButton.setObjectName("OldRadioButton")
        self.NoBackupRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.NoBackupRadioButton.setGeometry(QtCore.QRect(470, 100, 81, 21))
        self.NoBackupRadioButton.setObjectName("NoBackupRadioButton")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 91, 51))
        self.label_4.setObjectName("label_4")
        self.WorldNameEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.WorldNameEdit.setGeometry(QtCore.QRect(270, 20, 291, 21))
        self.WorldNameEdit.setReadOnly(False)
        self.WorldNameEdit.setObjectName("WorldNameEdit")
        self.groupBox_4 = QtWidgets.QGroupBox(self.General)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 260, 591, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 201, 41))
        self.label_5.setObjectName("label_5")
        self.TrayCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.TrayCheckBox.setGeometry(QtCore.QRect(250, 25, 21, 31))
        self.TrayCheckBox.setText("")
        self.TrayCheckBox.setObjectName("TrayRadioButton")
        self.tabWidget.addTab(self.General, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Google Drive Preference"))
        self.label.setText(_translate("Form", "Save File Folder ID (see URL)"))
        self.groupBox_2.setTitle(_translate("Form", "Local File Preference"))
        self.SelectSaveFilePathButton.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "Save file path"))
        self.label_3.setText(_translate("Form", "Backup File Style"))
        self.TimeRadioButton.setText(_translate("Form", "Time"))
        self.OldRadioButton.setText(_translate("Form", ".old"))
        self.NoBackupRadioButton.setText(_translate("Form", "No Backup"))
        self.label_4.setText(_translate("Form", "World name"))
        self.groupBox_4.setTitle(_translate("Form", "Background "))
        self.label_5.setText(_translate("Form", "Minimize to system tray on close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), _translate("Form", "General"))

